import NavBar from "@/components/NavBar";
import { ClerkProvider, SignedIn, SignedOut } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter, Outfit } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

const inter = Outfit({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Crocs fun",
  description: "Generated by create crocs fun site",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <SignedIn>
          <NavBar/>
            {children}
          </SignedIn>
          <SignedOut>
          </SignedOut>
        </body>
     </html>
    </ClerkProvider>

  );
}
